project_name: metronous
version: 1
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
release:
  github:
    owner: kiosvantra
    name: metronous
  draft: false
  prerelease: auto
  extra_files:
    - glob: ./install.sh
builds:
  - id: metronous
    binary: metronous
    main: ./cmd/metronous
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/kiosvantra/metronous/internal/version.Version={{ .Version }}
